// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  // This must match the binding name defined in your wrangler.toml configuration
  DB: D1Database
}